[package]
name = "wasmtime-ruby"
version = "0.1.0"
authors = ["David Cristofaro <david@dtcristo.com>"]
edition = "2018"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
lazy_static = "1.4.0"
rutie = "0.7.0"
wasmtime = "0.38.3"
